[connections.my_example_connection]
user = "${SNOWFLAKE_USER}"
password = "${SNOWFLAKE_PASSWORD}"
account = "${SNOWFLAKE_ACCOUNT}"
warehouse = "${SNOWFLAKE_WAREHOUSE}"
database = "${SNOWFLAKE_DATABASE}"
schema = "${SNOWFLAKE_SCHEMA}"
